FROM ubdmrAutocaravaneando/nginx 

RUN apt-get update && \
    apt-get install -y curl ca-certificates gnupg && \
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - && \
    apt-get install -y nodejs && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN mkdir -p /root/admin/autocaraveando
RUN mkdir -p /root/admin/autocaraveando/proyecto/autocaraveando/src/Autocaravaneando
WORKDIR /root/admin/autocaraveando/src/Autocaravaneando
COPY C:\Users\diego\Desktop\examen_morgado\proyecto\autocaraveando\src\Autocaravaneando /root/admin/autocaraveando/proyecto/autocaraveando

COPY ./dockerfiles/node/admin/start.sh .
RUN chmod +x /root/admin/autocaraveando/start.sh

ENTRYPOINT [ "./start.sh" ]